### ISSUE TITLE
How do you clear your manual prompts?

### ISSUE THREAD

**Issue by Arkanosmalkier** [tritant/sd-webui-creaprompt#5]
Liking this tool so far, but how do you clear your manual prompts?  I was clicking around testing things and the manual prompts I picked can't be cleared or reset?

When I try to use it, it remembers the past manual prompts, and adds my new selections to the old one.

I'm probably using it wrong, but please help? 

![image](https://github.com/tritant/sd-webui-creaprompt/assets/16632592/afbc8dec-8ff3-4e75-b091-abd63b13d3de)

**Comment by tritant** [comment]
Hello, this happens when you refresh the browser page.
Currently the only solution is to restart the console.
You must use None selection to the dropdown menu for remove the selection, don't refresh browser.
In the next version there will be a button to reset everything ;)

![image](https://github.com/tritant/sd-webui-creaprompt/assets/15909062/a7cbc8a0-2fc5-4b3e-ac08-f57d5c401b71)


![424860204_10161376420719059_7579930831088265698_n](https://github.com/tritant/sd-webui-creaprompt/assets/15909062/b06f5eb8-3911-467c-bd66-35b8ed5b31c2)

**Comment by tritant** [comment]
You can update to the new version with the reset button
